package com.ronglian.security.model;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.type.Alias;

@Alias("SysResource")
public class SysResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.RESOURCE_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.RESOURCE_NAME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String resourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.RESOURCE_DESCRIPTION
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String resourceDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.RESOURCE_URL
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String resourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.RESOURCE_SEQ
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private Integer resourceSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.RESOURCE_PARENTID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String resourceParentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.RESOURCE_TYPE
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.FLAG
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private Byte flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.ADDTIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.ADDBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String addby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.UPDATETIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.UPDATEBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String updateby;

    private boolean hasMenu = false;
    
    private String ResourceIcon;

	private List<SysResource> subResources;
	
	private String treeType; //构造ace-tree树状结构，tree-type为floder或item
	
    public String getTreeType() {
		return treeType;
	}

	public void setTreeType(String treeType) {
		this.treeType = treeType;
	}

	public String getResourceIcon() {
		return ResourceIcon;
	}

	public void setResourceIcon(String resourceIcon) {
		ResourceIcon = resourceIcon;
	}

	public List<SysResource> getSubResources() {
		return subResources;
	}

	public void setSubResources(List<SysResource> subResources) {
		this.subResources = subResources;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.RESOURCE_ID
     *
     * @return the value of sys_resource.RESOURCE_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.RESOURCE_ID
     *
     * @param resourceId the value for sys_resource.RESOURCE_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.RESOURCE_NAME
     *
     * @return the value of sys_resource.RESOURCE_NAME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.RESOURCE_NAME
     *
     * @param resourceName the value for sys_resource.RESOURCE_NAME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.RESOURCE_DESCRIPTION
     *
     * @return the value of sys_resource.RESOURCE_DESCRIPTION
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getResourceDescription() {
        return resourceDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.RESOURCE_DESCRIPTION
     *
     * @param resourceDescription the value for sys_resource.RESOURCE_DESCRIPTION
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setResourceDescription(String resourceDescription) {
        this.resourceDescription = resourceDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.RESOURCE_URL
     *
     * @return the value of sys_resource.RESOURCE_URL
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.RESOURCE_URL
     *
     * @param resourceUrl the value for sys_resource.RESOURCE_URL
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.RESOURCE_SEQ
     *
     * @return the value of sys_resource.RESOURCE_SEQ
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Integer getResourceSeq() {
        return resourceSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.RESOURCE_SEQ
     *
     * @param resourceSeq the value for sys_resource.RESOURCE_SEQ
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setResourceSeq(Integer resourceSeq) {
        this.resourceSeq = resourceSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.RESOURCE_PARENTID
     *
     * @return the value of sys_resource.RESOURCE_PARENTID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getResourceParentid() {
        return resourceParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.RESOURCE_PARENTID
     *
     * @param resourceParentid the value for sys_resource.RESOURCE_PARENTID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setResourceParentid(String resourceParentid) {
        this.resourceParentid = resourceParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.RESOURCE_TYPE
     *
     * @return the value of sys_resource.RESOURCE_TYPE
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.RESOURCE_TYPE
     *
     * @param resourceType the value for sys_resource.RESOURCE_TYPE
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.FLAG
     *
     * @return the value of sys_resource.FLAG
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.FLAG
     *
     * @param flag the value for sys_resource.FLAG
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.ADDTIME
     *
     * @return the value of sys_resource.ADDTIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.ADDTIME
     *
     * @param addtime the value for sys_resource.ADDTIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.ADDBY
     *
     * @return the value of sys_resource.ADDBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getAddby() {
        return addby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.ADDBY
     *
     * @param addby the value for sys_resource.ADDBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setAddby(String addby) {
        this.addby = addby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.UPDATETIME
     *
     * @return the value of sys_resource.UPDATETIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.UPDATETIME
     *
     * @param updatetime the value for sys_resource.UPDATETIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.UPDATEBY
     *
     * @return the value of sys_resource.UPDATEBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.UPDATEBY
     *
     * @param updateby the value for sys_resource.UPDATEBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }
    
    public boolean isHasMenu() {
		return hasMenu;
	}

	public void setHasMenu(boolean hasMenu) {
		this.hasMenu = hasMenu;
	}
}