package com.ronglian.security.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysResourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public SysResourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andResourceIdIsNull() {
            addCriterion("RESOURCE_ID is null");
            return (Criteria) this;
        }

        public Criteria andResourceIdIsNotNull() {
            addCriterion("RESOURCE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andResourceIdEqualTo(String value) {
            addCriterion("RESOURCE_ID =", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdNotEqualTo(String value) {
            addCriterion("RESOURCE_ID <>", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdGreaterThan(String value) {
            addCriterion("RESOURCE_ID >", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdGreaterThanOrEqualTo(String value) {
            addCriterion("RESOURCE_ID >=", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdLessThan(String value) {
            addCriterion("RESOURCE_ID <", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdLessThanOrEqualTo(String value) {
            addCriterion("RESOURCE_ID <=", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdLike(String value) {
            addCriterion("RESOURCE_ID like", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdNotLike(String value) {
            addCriterion("RESOURCE_ID not like", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdIn(List<String> values) {
            addCriterion("RESOURCE_ID in", values, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdNotIn(List<String> values) {
            addCriterion("RESOURCE_ID not in", values, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdBetween(String value1, String value2) {
            addCriterion("RESOURCE_ID between", value1, value2, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdNotBetween(String value1, String value2) {
            addCriterion("RESOURCE_ID not between", value1, value2, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceNameIsNull() {
            addCriterion("RESOURCE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andResourceNameIsNotNull() {
            addCriterion("RESOURCE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andResourceNameEqualTo(String value) {
            addCriterion("RESOURCE_NAME =", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameNotEqualTo(String value) {
            addCriterion("RESOURCE_NAME <>", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameGreaterThan(String value) {
            addCriterion("RESOURCE_NAME >", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameGreaterThanOrEqualTo(String value) {
            addCriterion("RESOURCE_NAME >=", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameLessThan(String value) {
            addCriterion("RESOURCE_NAME <", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameLessThanOrEqualTo(String value) {
            addCriterion("RESOURCE_NAME <=", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameLike(String value) {
            addCriterion("RESOURCE_NAME like", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameNotLike(String value) {
            addCriterion("RESOURCE_NAME not like", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameIn(List<String> values) {
            addCriterion("RESOURCE_NAME in", values, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameNotIn(List<String> values) {
            addCriterion("RESOURCE_NAME not in", values, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameBetween(String value1, String value2) {
            addCriterion("RESOURCE_NAME between", value1, value2, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameNotBetween(String value1, String value2) {
            addCriterion("RESOURCE_NAME not between", value1, value2, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionIsNull() {
            addCriterion("RESOURCE_DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionIsNotNull() {
            addCriterion("RESOURCE_DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionEqualTo(String value) {
            addCriterion("RESOURCE_DESCRIPTION =", value, "resourceDescription");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionNotEqualTo(String value) {
            addCriterion("RESOURCE_DESCRIPTION <>", value, "resourceDescription");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionGreaterThan(String value) {
            addCriterion("RESOURCE_DESCRIPTION >", value, "resourceDescription");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("RESOURCE_DESCRIPTION >=", value, "resourceDescription");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionLessThan(String value) {
            addCriterion("RESOURCE_DESCRIPTION <", value, "resourceDescription");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionLessThanOrEqualTo(String value) {
            addCriterion("RESOURCE_DESCRIPTION <=", value, "resourceDescription");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionLike(String value) {
            addCriterion("RESOURCE_DESCRIPTION like", value, "resourceDescription");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionNotLike(String value) {
            addCriterion("RESOURCE_DESCRIPTION not like", value, "resourceDescription");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionIn(List<String> values) {
            addCriterion("RESOURCE_DESCRIPTION in", values, "resourceDescription");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionNotIn(List<String> values) {
            addCriterion("RESOURCE_DESCRIPTION not in", values, "resourceDescription");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionBetween(String value1, String value2) {
            addCriterion("RESOURCE_DESCRIPTION between", value1, value2, "resourceDescription");
            return (Criteria) this;
        }

        public Criteria andResourceDescriptionNotBetween(String value1, String value2) {
            addCriterion("RESOURCE_DESCRIPTION not between", value1, value2, "resourceDescription");
            return (Criteria) this;
        }

        public Criteria andResourceUrlIsNull() {
            addCriterion("RESOURCE_URL is null");
            return (Criteria) this;
        }

        public Criteria andResourceUrlIsNotNull() {
            addCriterion("RESOURCE_URL is not null");
            return (Criteria) this;
        }

        public Criteria andResourceUrlEqualTo(String value) {
            addCriterion("RESOURCE_URL =", value, "resourceUrl");
            return (Criteria) this;
        }

        public Criteria andResourceUrlNotEqualTo(String value) {
            addCriterion("RESOURCE_URL <>", value, "resourceUrl");
            return (Criteria) this;
        }

        public Criteria andResourceUrlGreaterThan(String value) {
            addCriterion("RESOURCE_URL >", value, "resourceUrl");
            return (Criteria) this;
        }

        public Criteria andResourceUrlGreaterThanOrEqualTo(String value) {
            addCriterion("RESOURCE_URL >=", value, "resourceUrl");
            return (Criteria) this;
        }

        public Criteria andResourceUrlLessThan(String value) {
            addCriterion("RESOURCE_URL <", value, "resourceUrl");
            return (Criteria) this;
        }

        public Criteria andResourceUrlLessThanOrEqualTo(String value) {
            addCriterion("RESOURCE_URL <=", value, "resourceUrl");
            return (Criteria) this;
        }

        public Criteria andResourceUrlLike(String value) {
            addCriterion("RESOURCE_URL like", value, "resourceUrl");
            return (Criteria) this;
        }

        public Criteria andResourceUrlNotLike(String value) {
            addCriterion("RESOURCE_URL not like", value, "resourceUrl");
            return (Criteria) this;
        }

        public Criteria andResourceUrlIn(List<String> values) {
            addCriterion("RESOURCE_URL in", values, "resourceUrl");
            return (Criteria) this;
        }

        public Criteria andResourceUrlNotIn(List<String> values) {
            addCriterion("RESOURCE_URL not in", values, "resourceUrl");
            return (Criteria) this;
        }

        public Criteria andResourceUrlBetween(String value1, String value2) {
            addCriterion("RESOURCE_URL between", value1, value2, "resourceUrl");
            return (Criteria) this;
        }

        public Criteria andResourceUrlNotBetween(String value1, String value2) {
            addCriterion("RESOURCE_URL not between", value1, value2, "resourceUrl");
            return (Criteria) this;
        }

        public Criteria andResourceSeqIsNull() {
            addCriterion("RESOURCE_SEQ is null");
            return (Criteria) this;
        }

        public Criteria andResourceSeqIsNotNull() {
            addCriterion("RESOURCE_SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andResourceSeqEqualTo(Integer value) {
            addCriterion("RESOURCE_SEQ =", value, "resourceSeq");
            return (Criteria) this;
        }

        public Criteria andResourceSeqNotEqualTo(Integer value) {
            addCriterion("RESOURCE_SEQ <>", value, "resourceSeq");
            return (Criteria) this;
        }

        public Criteria andResourceSeqGreaterThan(Integer value) {
            addCriterion("RESOURCE_SEQ >", value, "resourceSeq");
            return (Criteria) this;
        }

        public Criteria andResourceSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("RESOURCE_SEQ >=", value, "resourceSeq");
            return (Criteria) this;
        }

        public Criteria andResourceSeqLessThan(Integer value) {
            addCriterion("RESOURCE_SEQ <", value, "resourceSeq");
            return (Criteria) this;
        }

        public Criteria andResourceSeqLessThanOrEqualTo(Integer value) {
            addCriterion("RESOURCE_SEQ <=", value, "resourceSeq");
            return (Criteria) this;
        }

        public Criteria andResourceSeqIn(List<Integer> values) {
            addCriterion("RESOURCE_SEQ in", values, "resourceSeq");
            return (Criteria) this;
        }

        public Criteria andResourceSeqNotIn(List<Integer> values) {
            addCriterion("RESOURCE_SEQ not in", values, "resourceSeq");
            return (Criteria) this;
        }

        public Criteria andResourceSeqBetween(Integer value1, Integer value2) {
            addCriterion("RESOURCE_SEQ between", value1, value2, "resourceSeq");
            return (Criteria) this;
        }

        public Criteria andResourceSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("RESOURCE_SEQ not between", value1, value2, "resourceSeq");
            return (Criteria) this;
        }

        public Criteria andResourceParentidIsNull() {
            addCriterion("RESOURCE_PARENTID is null");
            return (Criteria) this;
        }

        public Criteria andResourceParentidIsNotNull() {
            addCriterion("RESOURCE_PARENTID is not null");
            return (Criteria) this;
        }

        public Criteria andResourceParentidEqualTo(String value) {
            addCriterion("RESOURCE_PARENTID =", value, "resourceParentid");
            return (Criteria) this;
        }

        public Criteria andResourceParentidNotEqualTo(String value) {
            addCriterion("RESOURCE_PARENTID <>", value, "resourceParentid");
            return (Criteria) this;
        }

        public Criteria andResourceParentidGreaterThan(String value) {
            addCriterion("RESOURCE_PARENTID >", value, "resourceParentid");
            return (Criteria) this;
        }

        public Criteria andResourceParentidGreaterThanOrEqualTo(String value) {
            addCriterion("RESOURCE_PARENTID >=", value, "resourceParentid");
            return (Criteria) this;
        }

        public Criteria andResourceParentidLessThan(String value) {
            addCriterion("RESOURCE_PARENTID <", value, "resourceParentid");
            return (Criteria) this;
        }

        public Criteria andResourceParentidLessThanOrEqualTo(String value) {
            addCriterion("RESOURCE_PARENTID <=", value, "resourceParentid");
            return (Criteria) this;
        }

        public Criteria andResourceParentidLike(String value) {
            addCriterion("RESOURCE_PARENTID like", value, "resourceParentid");
            return (Criteria) this;
        }

        public Criteria andResourceParentidNotLike(String value) {
            addCriterion("RESOURCE_PARENTID not like", value, "resourceParentid");
            return (Criteria) this;
        }

        public Criteria andResourceParentidIn(List<String> values) {
            addCriterion("RESOURCE_PARENTID in", values, "resourceParentid");
            return (Criteria) this;
        }

        public Criteria andResourceParentidNotIn(List<String> values) {
            addCriterion("RESOURCE_PARENTID not in", values, "resourceParentid");
            return (Criteria) this;
        }

        public Criteria andResourceParentidBetween(String value1, String value2) {
            addCriterion("RESOURCE_PARENTID between", value1, value2, "resourceParentid");
            return (Criteria) this;
        }

        public Criteria andResourceParentidNotBetween(String value1, String value2) {
            addCriterion("RESOURCE_PARENTID not between", value1, value2, "resourceParentid");
            return (Criteria) this;
        }

        public Criteria andResourceTypeIsNull() {
            addCriterion("RESOURCE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andResourceTypeIsNotNull() {
            addCriterion("RESOURCE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andResourceTypeEqualTo(String value) {
            addCriterion("RESOURCE_TYPE =", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotEqualTo(String value) {
            addCriterion("RESOURCE_TYPE <>", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeGreaterThan(String value) {
            addCriterion("RESOURCE_TYPE >", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("RESOURCE_TYPE >=", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeLessThan(String value) {
            addCriterion("RESOURCE_TYPE <", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeLessThanOrEqualTo(String value) {
            addCriterion("RESOURCE_TYPE <=", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeLike(String value) {
            addCriterion("RESOURCE_TYPE like", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotLike(String value) {
            addCriterion("RESOURCE_TYPE not like", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeIn(List<String> values) {
            addCriterion("RESOURCE_TYPE in", values, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotIn(List<String> values) {
            addCriterion("RESOURCE_TYPE not in", values, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeBetween(String value1, String value2) {
            addCriterion("RESOURCE_TYPE between", value1, value2, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotBetween(String value1, String value2) {
            addCriterion("RESOURCE_TYPE not between", value1, value2, "resourceType");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("FLAG is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Byte value) {
            addCriterion("FLAG =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Byte value) {
            addCriterion("FLAG <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Byte value) {
            addCriterion("FLAG >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("FLAG >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Byte value) {
            addCriterion("FLAG <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Byte value) {
            addCriterion("FLAG <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Byte> values) {
            addCriterion("FLAG in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Byte> values) {
            addCriterion("FLAG not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Byte value1, Byte value2) {
            addCriterion("FLAG between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("FLAG not between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNull() {
            addCriterion("ADDTIME is null");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNotNull() {
            addCriterion("ADDTIME is not null");
            return (Criteria) this;
        }

        public Criteria andAddtimeEqualTo(Date value) {
            addCriterion("ADDTIME =", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotEqualTo(Date value) {
            addCriterion("ADDTIME <>", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThan(Date value) {
            addCriterion("ADDTIME >", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADDTIME >=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThan(Date value) {
            addCriterion("ADDTIME <", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThanOrEqualTo(Date value) {
            addCriterion("ADDTIME <=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeIn(List<Date> values) {
            addCriterion("ADDTIME in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotIn(List<Date> values) {
            addCriterion("ADDTIME not in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeBetween(Date value1, Date value2) {
            addCriterion("ADDTIME between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotBetween(Date value1, Date value2) {
            addCriterion("ADDTIME not between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddbyIsNull() {
            addCriterion("ADDBY is null");
            return (Criteria) this;
        }

        public Criteria andAddbyIsNotNull() {
            addCriterion("ADDBY is not null");
            return (Criteria) this;
        }

        public Criteria andAddbyEqualTo(String value) {
            addCriterion("ADDBY =", value, "addby");
            return (Criteria) this;
        }

        public Criteria andAddbyNotEqualTo(String value) {
            addCriterion("ADDBY <>", value, "addby");
            return (Criteria) this;
        }

        public Criteria andAddbyGreaterThan(String value) {
            addCriterion("ADDBY >", value, "addby");
            return (Criteria) this;
        }

        public Criteria andAddbyGreaterThanOrEqualTo(String value) {
            addCriterion("ADDBY >=", value, "addby");
            return (Criteria) this;
        }

        public Criteria andAddbyLessThan(String value) {
            addCriterion("ADDBY <", value, "addby");
            return (Criteria) this;
        }

        public Criteria andAddbyLessThanOrEqualTo(String value) {
            addCriterion("ADDBY <=", value, "addby");
            return (Criteria) this;
        }

        public Criteria andAddbyLike(String value) {
            addCriterion("ADDBY like", value, "addby");
            return (Criteria) this;
        }

        public Criteria andAddbyNotLike(String value) {
            addCriterion("ADDBY not like", value, "addby");
            return (Criteria) this;
        }

        public Criteria andAddbyIn(List<String> values) {
            addCriterion("ADDBY in", values, "addby");
            return (Criteria) this;
        }

        public Criteria andAddbyNotIn(List<String> values) {
            addCriterion("ADDBY not in", values, "addby");
            return (Criteria) this;
        }

        public Criteria andAddbyBetween(String value1, String value2) {
            addCriterion("ADDBY between", value1, value2, "addby");
            return (Criteria) this;
        }

        public Criteria andAddbyNotBetween(String value1, String value2) {
            addCriterion("ADDBY not between", value1, value2, "addby");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("UPDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("UPDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("UPDATETIME =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("UPDATETIME <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("UPDATETIME >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATETIME >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("UPDATETIME <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATETIME <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("UPDATETIME in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("UPDATETIME not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("UPDATETIME between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATETIME not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNull() {
            addCriterion("UPDATEBY is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNotNull() {
            addCriterion("UPDATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyEqualTo(String value) {
            addCriterion("UPDATEBY =", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotEqualTo(String value) {
            addCriterion("UPDATEBY <>", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThan(String value) {
            addCriterion("UPDATEBY >", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATEBY >=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThan(String value) {
            addCriterion("UPDATEBY <", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThanOrEqualTo(String value) {
            addCriterion("UPDATEBY <=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLike(String value) {
            addCriterion("UPDATEBY like", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotLike(String value) {
            addCriterion("UPDATEBY not like", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIn(List<String> values) {
            addCriterion("UPDATEBY in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotIn(List<String> values) {
            addCriterion("UPDATEBY not in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyBetween(String value1, String value2) {
            addCriterion("UPDATEBY between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotBetween(String value1, String value2) {
            addCriterion("UPDATEBY not between", value1, value2, "updateby");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_resource
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 13 16:33:37 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}