package com.ronglian.security.model;

import java.util.Date;

import org.apache.ibatis.type.Alias;

@Alias("SysRoles")
public class SysRoles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ROLE_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ROLE_NAME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ROLE_DESCRIPTION
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String roleDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ROLE_SEQ
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private Integer roleSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.FLAG
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private Byte flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ADDTIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ADDBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String addby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.UPDATETIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.UPDATEBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ROLE_ID
     *
     * @return the value of sys_roles.ROLE_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ROLE_ID
     *
     * @param roleId the value for sys_roles.ROLE_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ROLE_NAME
     *
     * @return the value of sys_roles.ROLE_NAME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ROLE_NAME
     *
     * @param roleName the value for sys_roles.ROLE_NAME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ROLE_DESCRIPTION
     *
     * @return the value of sys_roles.ROLE_DESCRIPTION
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getRoleDescription() {
        return roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ROLE_DESCRIPTION
     *
     * @param roleDescription the value for sys_roles.ROLE_DESCRIPTION
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ROLE_SEQ
     *
     * @return the value of sys_roles.ROLE_SEQ
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Integer getRoleSeq() {
        return roleSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ROLE_SEQ
     *
     * @param roleSeq the value for sys_roles.ROLE_SEQ
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setRoleSeq(Integer roleSeq) {
        this.roleSeq = roleSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.FLAG
     *
     * @return the value of sys_roles.FLAG
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.FLAG
     *
     * @param flag the value for sys_roles.FLAG
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ADDTIME
     *
     * @return the value of sys_roles.ADDTIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ADDTIME
     *
     * @param addtime the value for sys_roles.ADDTIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ADDBY
     *
     * @return the value of sys_roles.ADDBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getAddby() {
        return addby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ADDBY
     *
     * @param addby the value for sys_roles.ADDBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setAddby(String addby) {
        this.addby = addby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.UPDATETIME
     *
     * @return the value of sys_roles.UPDATETIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.UPDATETIME
     *
     * @param updatetime the value for sys_roles.UPDATETIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.UPDATEBY
     *
     * @return the value of sys_roles.UPDATEBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.UPDATEBY
     *
     * @param updateby the value for sys_roles.UPDATEBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }
    
    private String hasRole;

	public String getHasRole() {
		return hasRole;
	}

	public void setHasRole(String hasRole) {
		this.hasRole = hasRole;
	}
    
    
}