package com.ronglian.security.model;

import java.util.Date;

import org.apache.ibatis.type.Alias;

@Alias("SysUserRoles")
public class SysUserRoles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_roles.ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_roles.USER_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_roles.ROLE_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_roles.FLAG
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private int flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_roles.ADDTIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_roles.ADDBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String addby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_roles.UPDATETIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_roles.UPDATEBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_roles.ID
     *
     * @return the value of sys_user_roles.ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_roles.ID
     *
     * @param id the value for sys_user_roles.ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_roles.USER_ID
     *
     * @return the value of sys_user_roles.USER_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_roles.USER_ID
     *
     * @param userId the value for sys_user_roles.USER_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_roles.ROLE_ID
     *
     * @return the value of sys_user_roles.ROLE_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_roles.ROLE_ID
     *
     * @param roleId the value for sys_user_roles.ROLE_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_roles.FLAG
     *
     * @return the value of sys_user_roles.FLAG
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public int getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_roles.FLAG
     *
     * @param flag the value for sys_user_roles.FLAG
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setFlag(int flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_roles.ADDTIME
     *
     * @return the value of sys_user_roles.ADDTIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_roles.ADDTIME
     *
     * @param addtime the value for sys_user_roles.ADDTIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_roles.ADDBY
     *
     * @return the value of sys_user_roles.ADDBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getAddby() {
        return addby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_roles.ADDBY
     *
     * @param addby the value for sys_user_roles.ADDBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setAddby(String addby) {
        this.addby = addby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_roles.UPDATETIME
     *
     * @return the value of sys_user_roles.UPDATETIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_roles.UPDATETIME
     *
     * @param updatetime the value for sys_user_roles.UPDATETIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_roles.UPDATEBY
     *
     * @return the value of sys_user_roles.UPDATEBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_roles.UPDATEBY
     *
     * @param updateby the value for sys_user_roles.UPDATEBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }
}