package com.ronglian.security.model;

import java.util.Date;

import org.apache.ibatis.type.Alias;

@Alias("SysUserOrganization")
public class SysUserOrganization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.USER_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.ORGANIZATION_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.FLAG
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private Byte flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.ADDTIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.ADDBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String addby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.UPDATETIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.UPDATEBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    private String updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.ID
     *
     * @return the value of sys_user_organization.ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.ID
     *
     * @param id the value for sys_user_organization.ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.USER_ID
     *
     * @return the value of sys_user_organization.USER_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.USER_ID
     *
     * @param userId the value for sys_user_organization.USER_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.ORGANIZATION_ID
     *
     * @return the value of sys_user_organization.ORGANIZATION_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.ORGANIZATION_ID
     *
     * @param organizationId the value for sys_user_organization.ORGANIZATION_ID
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.FLAG
     *
     * @return the value of sys_user_organization.FLAG
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.FLAG
     *
     * @param flag the value for sys_user_organization.FLAG
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.ADDTIME
     *
     * @return the value of sys_user_organization.ADDTIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.ADDTIME
     *
     * @param addtime the value for sys_user_organization.ADDTIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.ADDBY
     *
     * @return the value of sys_user_organization.ADDBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getAddby() {
        return addby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.ADDBY
     *
     * @param addby the value for sys_user_organization.ADDBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setAddby(String addby) {
        this.addby = addby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.UPDATETIME
     *
     * @return the value of sys_user_organization.UPDATETIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.UPDATETIME
     *
     * @param updatetime the value for sys_user_organization.UPDATETIME
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.UPDATEBY
     *
     * @return the value of sys_user_organization.UPDATEBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.UPDATEBY
     *
     * @param updateby the value for sys_user_organization.UPDATEBY
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }
}