package com.ronglian.ch.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DiagnosticCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public DiagnosticCategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdIsNull() {
            addCriterion("DIAGNOSTIC_ID is null");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdIsNotNull() {
            addCriterion("DIAGNOSTIC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdEqualTo(String value) {
            addCriterion("DIAGNOSTIC_ID =", value, "diagnosticId");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdNotEqualTo(String value) {
            addCriterion("DIAGNOSTIC_ID <>", value, "diagnosticId");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdGreaterThan(String value) {
            addCriterion("DIAGNOSTIC_ID >", value, "diagnosticId");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdGreaterThanOrEqualTo(String value) {
            addCriterion("DIAGNOSTIC_ID >=", value, "diagnosticId");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdLessThan(String value) {
            addCriterion("DIAGNOSTIC_ID <", value, "diagnosticId");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdLessThanOrEqualTo(String value) {
            addCriterion("DIAGNOSTIC_ID <=", value, "diagnosticId");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdLike(String value) {
            addCriterion("DIAGNOSTIC_ID like", value, "diagnosticId");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdNotLike(String value) {
            addCriterion("DIAGNOSTIC_ID not like", value, "diagnosticId");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdIn(List<String> values) {
            addCriterion("DIAGNOSTIC_ID in", values, "diagnosticId");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdNotIn(List<String> values) {
            addCriterion("DIAGNOSTIC_ID not in", values, "diagnosticId");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdBetween(String value1, String value2) {
            addCriterion("DIAGNOSTIC_ID between", value1, value2, "diagnosticId");
            return (Criteria) this;
        }

        public Criteria andDiagnosticIdNotBetween(String value1, String value2) {
            addCriterion("DIAGNOSTIC_ID not between", value1, value2, "diagnosticId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNull() {
            addCriterion("PATIENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNotNull() {
            addCriterion("PATIENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPatientIdEqualTo(String value) {
            addCriterion("PATIENT_ID =", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotEqualTo(String value) {
            addCriterion("PATIENT_ID <>", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThan(String value) {
            addCriterion("PATIENT_ID >", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThanOrEqualTo(String value) {
            addCriterion("PATIENT_ID >=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThan(String value) {
            addCriterion("PATIENT_ID <", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThanOrEqualTo(String value) {
            addCriterion("PATIENT_ID <=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLike(String value) {
            addCriterion("PATIENT_ID like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotLike(String value) {
            addCriterion("PATIENT_ID not like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIn(List<String> values) {
            addCriterion("PATIENT_ID in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotIn(List<String> values) {
            addCriterion("PATIENT_ID not in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdBetween(String value1, String value2) {
            addCriterion("PATIENT_ID between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotBetween(String value1, String value2) {
            addCriterion("PATIENT_ID not between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andVisitIdIsNull() {
            addCriterion("VISIT_ID is null");
            return (Criteria) this;
        }

        public Criteria andVisitIdIsNotNull() {
            addCriterion("VISIT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andVisitIdEqualTo(Integer value) {
            addCriterion("VISIT_ID =", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdNotEqualTo(Integer value) {
            addCriterion("VISIT_ID <>", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdGreaterThan(Integer value) {
            addCriterion("VISIT_ID >", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("VISIT_ID >=", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdLessThan(Integer value) {
            addCriterion("VISIT_ID <", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdLessThanOrEqualTo(Integer value) {
            addCriterion("VISIT_ID <=", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdIn(List<Integer> values) {
            addCriterion("VISIT_ID in", values, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdNotIn(List<Integer> values) {
            addCriterion("VISIT_ID not in", values, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdBetween(Integer value1, Integer value2) {
            addCriterion("VISIT_ID between", value1, value2, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdNotBetween(Integer value1, Integer value2) {
            addCriterion("VISIT_ID not between", value1, value2, "visitId");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeIsNull() {
            addCriterion("DIAGNOSIS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeIsNotNull() {
            addCriterion("DIAGNOSIS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeEqualTo(String value) {
            addCriterion("DIAGNOSIS_TYPE =", value, "diagnosisType");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeNotEqualTo(String value) {
            addCriterion("DIAGNOSIS_TYPE <>", value, "diagnosisType");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeGreaterThan(String value) {
            addCriterion("DIAGNOSIS_TYPE >", value, "diagnosisType");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DIAGNOSIS_TYPE >=", value, "diagnosisType");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeLessThan(String value) {
            addCriterion("DIAGNOSIS_TYPE <", value, "diagnosisType");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeLessThanOrEqualTo(String value) {
            addCriterion("DIAGNOSIS_TYPE <=", value, "diagnosisType");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeLike(String value) {
            addCriterion("DIAGNOSIS_TYPE like", value, "diagnosisType");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeNotLike(String value) {
            addCriterion("DIAGNOSIS_TYPE not like", value, "diagnosisType");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeIn(List<String> values) {
            addCriterion("DIAGNOSIS_TYPE in", values, "diagnosisType");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeNotIn(List<String> values) {
            addCriterion("DIAGNOSIS_TYPE not in", values, "diagnosisType");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeBetween(String value1, String value2) {
            addCriterion("DIAGNOSIS_TYPE between", value1, value2, "diagnosisType");
            return (Criteria) this;
        }

        public Criteria andDiagnosisTypeNotBetween(String value1, String value2) {
            addCriterion("DIAGNOSIS_TYPE not between", value1, value2, "diagnosisType");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNoIsNull() {
            addCriterion("DIAGNOSIS_NO is null");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNoIsNotNull() {
            addCriterion("DIAGNOSIS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNoEqualTo(Integer value) {
            addCriterion("DIAGNOSIS_NO =", value, "diagnosisNo");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNoNotEqualTo(Integer value) {
            addCriterion("DIAGNOSIS_NO <>", value, "diagnosisNo");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNoGreaterThan(Integer value) {
            addCriterion("DIAGNOSIS_NO >", value, "diagnosisNo");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("DIAGNOSIS_NO >=", value, "diagnosisNo");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNoLessThan(Integer value) {
            addCriterion("DIAGNOSIS_NO <", value, "diagnosisNo");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNoLessThanOrEqualTo(Integer value) {
            addCriterion("DIAGNOSIS_NO <=", value, "diagnosisNo");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNoIn(List<Integer> values) {
            addCriterion("DIAGNOSIS_NO in", values, "diagnosisNo");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNoNotIn(List<Integer> values) {
            addCriterion("DIAGNOSIS_NO not in", values, "diagnosisNo");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNoBetween(Integer value1, Integer value2) {
            addCriterion("DIAGNOSIS_NO between", value1, value2, "diagnosisNo");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNoNotBetween(Integer value1, Integer value2) {
            addCriterion("DIAGNOSIS_NO not between", value1, value2, "diagnosisNo");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChIsNull() {
            addCriterion("DIAGNOSIS_CODE_CH is null");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChIsNotNull() {
            addCriterion("DIAGNOSIS_CODE_CH is not null");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChEqualTo(String value) {
            addCriterion("DIAGNOSIS_CODE_CH =", value, "diagnosisCodeCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChNotEqualTo(String value) {
            addCriterion("DIAGNOSIS_CODE_CH <>", value, "diagnosisCodeCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChGreaterThan(String value) {
            addCriterion("DIAGNOSIS_CODE_CH >", value, "diagnosisCodeCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChGreaterThanOrEqualTo(String value) {
            addCriterion("DIAGNOSIS_CODE_CH >=", value, "diagnosisCodeCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChLessThan(String value) {
            addCriterion("DIAGNOSIS_CODE_CH <", value, "diagnosisCodeCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChLessThanOrEqualTo(String value) {
            addCriterion("DIAGNOSIS_CODE_CH <=", value, "diagnosisCodeCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChLike(String value) {
            addCriterion("DIAGNOSIS_CODE_CH like", value, "diagnosisCodeCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChNotLike(String value) {
            addCriterion("DIAGNOSIS_CODE_CH not like", value, "diagnosisCodeCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChIn(List<String> values) {
            addCriterion("DIAGNOSIS_CODE_CH in", values, "diagnosisCodeCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChNotIn(List<String> values) {
            addCriterion("DIAGNOSIS_CODE_CH not in", values, "diagnosisCodeCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChBetween(String value1, String value2) {
            addCriterion("DIAGNOSIS_CODE_CH between", value1, value2, "diagnosisCodeCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeChNotBetween(String value1, String value2) {
            addCriterion("DIAGNOSIS_CODE_CH not between", value1, value2, "diagnosisCodeCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChIsNull() {
            addCriterion("DIAGNOSIS_CODE_ADD_CH is null");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChIsNotNull() {
            addCriterion("DIAGNOSIS_CODE_ADD_CH is not null");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChEqualTo(String value) {
            addCriterion("DIAGNOSIS_CODE_ADD_CH =", value, "diagnosisCodeAddCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChNotEqualTo(String value) {
            addCriterion("DIAGNOSIS_CODE_ADD_CH <>", value, "diagnosisCodeAddCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChGreaterThan(String value) {
            addCriterion("DIAGNOSIS_CODE_ADD_CH >", value, "diagnosisCodeAddCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChGreaterThanOrEqualTo(String value) {
            addCriterion("DIAGNOSIS_CODE_ADD_CH >=", value, "diagnosisCodeAddCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChLessThan(String value) {
            addCriterion("DIAGNOSIS_CODE_ADD_CH <", value, "diagnosisCodeAddCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChLessThanOrEqualTo(String value) {
            addCriterion("DIAGNOSIS_CODE_ADD_CH <=", value, "diagnosisCodeAddCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChLike(String value) {
            addCriterion("DIAGNOSIS_CODE_ADD_CH like", value, "diagnosisCodeAddCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChNotLike(String value) {
            addCriterion("DIAGNOSIS_CODE_ADD_CH not like", value, "diagnosisCodeAddCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChIn(List<String> values) {
            addCriterion("DIAGNOSIS_CODE_ADD_CH in", values, "diagnosisCodeAddCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChNotIn(List<String> values) {
            addCriterion("DIAGNOSIS_CODE_ADD_CH not in", values, "diagnosisCodeAddCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChBetween(String value1, String value2) {
            addCriterion("DIAGNOSIS_CODE_ADD_CH between", value1, value2, "diagnosisCodeAddCh");
            return (Criteria) this;
        }

        public Criteria andDiagnosisCodeAddChNotBetween(String value1, String value2) {
            addCriterion("DIAGNOSIS_CODE_ADD_CH not between", value1, value2, "diagnosisCodeAddCh");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("CREATEBY is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("CREATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(String value) {
            addCriterion("CREATEBY =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(String value) {
            addCriterion("CREATEBY <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(String value) {
            addCriterion("CREATEBY >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEBY >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(String value) {
            addCriterion("CREATEBY <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(String value) {
            addCriterion("CREATEBY <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLike(String value) {
            addCriterion("CREATEBY like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotLike(String value) {
            addCriterion("CREATEBY not like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<String> values) {
            addCriterion("CREATEBY in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<String> values) {
            addCriterion("CREATEBY not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(String value1, String value2) {
            addCriterion("CREATEBY between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(String value1, String value2) {
            addCriterion("CREATEBY not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNull() {
            addCriterion("UPDATEBY is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNotNull() {
            addCriterion("UPDATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyEqualTo(String value) {
            addCriterion("UPDATEBY =", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotEqualTo(String value) {
            addCriterion("UPDATEBY <>", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThan(String value) {
            addCriterion("UPDATEBY >", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATEBY >=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThan(String value) {
            addCriterion("UPDATEBY <", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThanOrEqualTo(String value) {
            addCriterion("UPDATEBY <=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLike(String value) {
            addCriterion("UPDATEBY like", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotLike(String value) {
            addCriterion("UPDATEBY not like", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIn(List<String> values) {
            addCriterion("UPDATEBY in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotIn(List<String> values) {
            addCriterion("UPDATEBY not in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyBetween(String value1, String value2) {
            addCriterion("UPDATEBY between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotBetween(String value1, String value2) {
            addCriterion("UPDATEBY not between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNull() {
            addCriterion("UPDATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNotNull() {
            addCriterion("UPDATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateEqualTo(Date value) {
            addCriterion("UPDATEDATE =", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotEqualTo(Date value) {
            addCriterion("UPDATEDATE <>", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThan(Date value) {
            addCriterion("UPDATEDATE >", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATEDATE >=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThan(Date value) {
            addCriterion("UPDATEDATE <", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATEDATE <=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIn(List<Date> values) {
            addCriterion("UPDATEDATE in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotIn(List<Date> values) {
            addCriterion("UPDATEDATE not in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateBetween(Date value1, Date value2) {
            addCriterion("UPDATEDATE between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATEDATE not between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("FLAG is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Integer value) {
            addCriterion("FLAG =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Integer value) {
            addCriterion("FLAG <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Integer value) {
            addCriterion("FLAG >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("FLAG >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Integer value) {
            addCriterion("FLAG <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Integer value) {
            addCriterion("FLAG <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Integer> values) {
            addCriterion("FLAG in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Integer> values) {
            addCriterion("FLAG not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Integer value1, Integer value2) {
            addCriterion("FLAG between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("FLAG not between", value1, value2, "flag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table diagnostic_category
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 07 14:27:05 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table diagnostic_category
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}