package com.ronglian.ch.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PatMasterTimerExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	public PatMasterTimerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPatientIdIsNull() {
			addCriterion("PATIENT_ID is null");
			return (Criteria) this;
		}

		public Criteria andPatientIdIsNotNull() {
			addCriterion("PATIENT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPatientIdEqualTo(String value) {
			addCriterion("PATIENT_ID =", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotEqualTo(String value) {
			addCriterion("PATIENT_ID <>", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdGreaterThan(String value) {
			addCriterion("PATIENT_ID >", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdGreaterThanOrEqualTo(String value) {
			addCriterion("PATIENT_ID >=", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLessThan(String value) {
			addCriterion("PATIENT_ID <", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLessThanOrEqualTo(String value) {
			addCriterion("PATIENT_ID <=", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLike(String value) {
			addCriterion("PATIENT_ID like", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotLike(String value) {
			addCriterion("PATIENT_ID not like", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdIn(List<String> values) {
			addCriterion("PATIENT_ID in", values, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotIn(List<String> values) {
			addCriterion("PATIENT_ID not in", values, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdBetween(String value1, String value2) {
			addCriterion("PATIENT_ID between", value1, value2, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotBetween(String value1, String value2) {
			addCriterion("PATIENT_ID not between", value1, value2, "patientId");
			return (Criteria) this;
		}

		public Criteria andTableIdIsNull() {
			addCriterion("TABLE_ID is null");
			return (Criteria) this;
		}

		public Criteria andTableIdIsNotNull() {
			addCriterion("TABLE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andTableIdEqualTo(String value) {
			addCriterion("TABLE_ID =", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdNotEqualTo(String value) {
			addCriterion("TABLE_ID <>", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdGreaterThan(String value) {
			addCriterion("TABLE_ID >", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdGreaterThanOrEqualTo(String value) {
			addCriterion("TABLE_ID >=", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdLessThan(String value) {
			addCriterion("TABLE_ID <", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdLessThanOrEqualTo(String value) {
			addCriterion("TABLE_ID <=", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdLike(String value) {
			addCriterion("TABLE_ID like", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdNotLike(String value) {
			addCriterion("TABLE_ID not like", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdIn(List<String> values) {
			addCriterion("TABLE_ID in", values, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdNotIn(List<String> values) {
			addCriterion("TABLE_ID not in", values, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdBetween(String value1, String value2) {
			addCriterion("TABLE_ID between", value1, value2, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdNotBetween(String value1, String value2) {
			addCriterion("TABLE_ID not between", value1, value2, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableNameIsNull() {
			addCriterion("TABLE_NAME is null");
			return (Criteria) this;
		}

		public Criteria andTableNameIsNotNull() {
			addCriterion("TABLE_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andTableNameEqualTo(String value) {
			addCriterion("TABLE_NAME =", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameNotEqualTo(String value) {
			addCriterion("TABLE_NAME <>", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameGreaterThan(String value) {
			addCriterion("TABLE_NAME >", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameGreaterThanOrEqualTo(String value) {
			addCriterion("TABLE_NAME >=", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameLessThan(String value) {
			addCriterion("TABLE_NAME <", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameLessThanOrEqualTo(String value) {
			addCriterion("TABLE_NAME <=", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameLike(String value) {
			addCriterion("TABLE_NAME like", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameNotLike(String value) {
			addCriterion("TABLE_NAME not like", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameIn(List<String> values) {
			addCriterion("TABLE_NAME in", values, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameNotIn(List<String> values) {
			addCriterion("TABLE_NAME not in", values, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameBetween(String value1, String value2) {
			addCriterion("TABLE_NAME between", value1, value2, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameNotBetween(String value1, String value2) {
			addCriterion("TABLE_NAME not between", value1, value2, "tableName");
			return (Criteria) this;
		}

		public Criteria andAbbreDescIsNull() {
			addCriterion("ABBRE_DESC is null");
			return (Criteria) this;
		}

		public Criteria andAbbreDescIsNotNull() {
			addCriterion("ABBRE_DESC is not null");
			return (Criteria) this;
		}

		public Criteria andAbbreDescEqualTo(String value) {
			addCriterion("ABBRE_DESC =", value, "abbreDesc");
			return (Criteria) this;
		}

		public Criteria andAbbreDescNotEqualTo(String value) {
			addCriterion("ABBRE_DESC <>", value, "abbreDesc");
			return (Criteria) this;
		}

		public Criteria andAbbreDescGreaterThan(String value) {
			addCriterion("ABBRE_DESC >", value, "abbreDesc");
			return (Criteria) this;
		}

		public Criteria andAbbreDescGreaterThanOrEqualTo(String value) {
			addCriterion("ABBRE_DESC >=", value, "abbreDesc");
			return (Criteria) this;
		}

		public Criteria andAbbreDescLessThan(String value) {
			addCriterion("ABBRE_DESC <", value, "abbreDesc");
			return (Criteria) this;
		}

		public Criteria andAbbreDescLessThanOrEqualTo(String value) {
			addCriterion("ABBRE_DESC <=", value, "abbreDesc");
			return (Criteria) this;
		}

		public Criteria andAbbreDescLike(String value) {
			addCriterion("ABBRE_DESC like", value, "abbreDesc");
			return (Criteria) this;
		}

		public Criteria andAbbreDescNotLike(String value) {
			addCriterion("ABBRE_DESC not like", value, "abbreDesc");
			return (Criteria) this;
		}

		public Criteria andAbbreDescIn(List<String> values) {
			addCriterion("ABBRE_DESC in", values, "abbreDesc");
			return (Criteria) this;
		}

		public Criteria andAbbreDescNotIn(List<String> values) {
			addCriterion("ABBRE_DESC not in", values, "abbreDesc");
			return (Criteria) this;
		}

		public Criteria andAbbreDescBetween(String value1, String value2) {
			addCriterion("ABBRE_DESC between", value1, value2, "abbreDesc");
			return (Criteria) this;
		}

		public Criteria andAbbreDescNotBetween(String value1, String value2) {
			addCriterion("ABBRE_DESC not between", value1, value2, "abbreDesc");
			return (Criteria) this;
		}

		public Criteria andAbbreNameIsNull() {
			addCriterion("ABBRE_NAME is null");
			return (Criteria) this;
		}

		public Criteria andAbbreNameIsNotNull() {
			addCriterion("ABBRE_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andAbbreNameEqualTo(String value) {
			addCriterion("ABBRE_NAME =", value, "abbreName");
			return (Criteria) this;
		}

		public Criteria andAbbreNameNotEqualTo(String value) {
			addCriterion("ABBRE_NAME <>", value, "abbreName");
			return (Criteria) this;
		}

		public Criteria andAbbreNameGreaterThan(String value) {
			addCriterion("ABBRE_NAME >", value, "abbreName");
			return (Criteria) this;
		}

		public Criteria andAbbreNameGreaterThanOrEqualTo(String value) {
			addCriterion("ABBRE_NAME >=", value, "abbreName");
			return (Criteria) this;
		}

		public Criteria andAbbreNameLessThan(String value) {
			addCriterion("ABBRE_NAME <", value, "abbreName");
			return (Criteria) this;
		}

		public Criteria andAbbreNameLessThanOrEqualTo(String value) {
			addCriterion("ABBRE_NAME <=", value, "abbreName");
			return (Criteria) this;
		}

		public Criteria andAbbreNameLike(String value) {
			addCriterion("ABBRE_NAME like", value, "abbreName");
			return (Criteria) this;
		}

		public Criteria andAbbreNameNotLike(String value) {
			addCriterion("ABBRE_NAME not like", value, "abbreName");
			return (Criteria) this;
		}

		public Criteria andAbbreNameIn(List<String> values) {
			addCriterion("ABBRE_NAME in", values, "abbreName");
			return (Criteria) this;
		}

		public Criteria andAbbreNameNotIn(List<String> values) {
			addCriterion("ABBRE_NAME not in", values, "abbreName");
			return (Criteria) this;
		}

		public Criteria andAbbreNameBetween(String value1, String value2) {
			addCriterion("ABBRE_NAME between", value1, value2, "abbreName");
			return (Criteria) this;
		}

		public Criteria andAbbreNameNotBetween(String value1, String value2) {
			addCriterion("ABBRE_NAME not between", value1, value2, "abbreName");
			return (Criteria) this;
		}

		public Criteria andOperatedateIsNull() {
			addCriterion("OPERATEDATE is null");
			return (Criteria) this;
		}

		public Criteria andOperatedateIsNotNull() {
			addCriterion("OPERATEDATE is not null");
			return (Criteria) this;
		}

		public Criteria andOperatedateEqualTo(Date value) {
			addCriterion("OPERATEDATE =", value, "operatedate");
			return (Criteria) this;
		}

		public Criteria andOperatedateNotEqualTo(Date value) {
			addCriterion("OPERATEDATE <>", value, "operatedate");
			return (Criteria) this;
		}

		public Criteria andOperatedateGreaterThan(Date value) {
			addCriterion("OPERATEDATE >", value, "operatedate");
			return (Criteria) this;
		}

		public Criteria andOperatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("OPERATEDATE >=", value, "operatedate");
			return (Criteria) this;
		}

		public Criteria andOperatedateLessThan(Date value) {
			addCriterion("OPERATEDATE <", value, "operatedate");
			return (Criteria) this;
		}

		public Criteria andOperatedateLessThanOrEqualTo(Date value) {
			addCriterion("OPERATEDATE <=", value, "operatedate");
			return (Criteria) this;
		}

		public Criteria andOperatedateIn(List<Date> values) {
			addCriterion("OPERATEDATE in", values, "operatedate");
			return (Criteria) this;
		}

		public Criteria andOperatedateNotIn(List<Date> values) {
			addCriterion("OPERATEDATE not in", values, "operatedate");
			return (Criteria) this;
		}

		public Criteria andOperatedateBetween(Date value1, Date value2) {
			addCriterion("OPERATEDATE between", value1, value2, "operatedate");
			return (Criteria) this;
		}

		public Criteria andOperatedateNotBetween(Date value1, Date value2) {
			addCriterion("OPERATEDATE not between", value1, value2,
					"operatedate");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("CREATEDATE is null");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("CREATEDATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterion("CREATEDATE =", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterion("CREATEDATE <>", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterion("CREATEDATE >", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATEDATE >=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterion("CREATEDATE <", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterion("CREATEDATE <=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateIn(List<Date> values) {
			addCriterion("CREATEDATE in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotIn(List<Date> values) {
			addCriterion("CREATEDATE not in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterion("CREATEDATE between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterion("CREATEDATE not between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateIsNull() {
			addCriterion("UPDATEDATE is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedateIsNotNull() {
			addCriterion("UPDATEDATE is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedateEqualTo(Date value) {
			addCriterion("UPDATEDATE =", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateNotEqualTo(Date value) {
			addCriterion("UPDATEDATE <>", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateGreaterThan(Date value) {
			addCriterion("UPDATEDATE >", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATEDATE >=", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateLessThan(Date value) {
			addCriterion("UPDATEDATE <", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
			addCriterion("UPDATEDATE <=", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateIn(List<Date> values) {
			addCriterion("UPDATEDATE in", values, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateNotIn(List<Date> values) {
			addCriterion("UPDATEDATE not in", values, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateBetween(Date value1, Date value2) {
			addCriterion("UPDATEDATE between", value1, value2, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
			addCriterion("UPDATEDATE not between", value1, value2, "updatedate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table patient_master_timer
	 * 
	 * @mbggenerated do_not_delete_during_merge Thu Sep 01 17:52:46 CST 2016
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table patient_master_timer
	 * 
	 * @mbggenerated Thu Sep 01 17:52:46 CST 2016
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}