package com.ronglian.ch.model;

import java.util.Date;

import org.apache.ibatis.type.Alias;

@Alias("PatMasterTimer")
public class PatMasterTimer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_master_timer.ID
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_master_timer.PATIENT_ID
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    private String patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_master_timer.TABLE_ID
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    private String tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_master_timer.TABLE_NAME
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_master_timer.ABBRE_DESC
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    private String abbreDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_master_timer.ABBRE_NAME
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    private String abbreName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_master_timer.OPERATEDATE
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    private Date operatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_master_timer.CREATEDATE
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_master_timer.UPDATEDATE
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_master_timer.ID
     *
     * @return the value of patient_master_timer.ID
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    private String outpatient_no;
    private String inpatient_no;
    
    
    
    public String getOutpatient_no() {
		return outpatient_no;
	}

	public void setOutpatient_no(String outpatient_no) {
		this.outpatient_no = outpatient_no;
	}

	public String getInpatient_no() {
		return inpatient_no;
	}

	public void setInpatient_no(String inpatient_no) {
		this.inpatient_no = inpatient_no;
	}

	public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_master_timer.ID
     *
     * @param id the value for patient_master_timer.ID
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_master_timer.PATIENT_ID
     *
     * @return the value of patient_master_timer.PATIENT_ID
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_master_timer.PATIENT_ID
     *
     * @param patientId the value for patient_master_timer.PATIENT_ID
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_master_timer.TABLE_ID
     *
     * @return the value of patient_master_timer.TABLE_ID
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public String getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_master_timer.TABLE_ID
     *
     * @param tableId the value for patient_master_timer.TABLE_ID
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public void setTableId(String tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_master_timer.TABLE_NAME
     *
     * @return the value of patient_master_timer.TABLE_NAME
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_master_timer.TABLE_NAME
     *
     * @param tableName the value for patient_master_timer.TABLE_NAME
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_master_timer.ABBRE_DESC
     *
     * @return the value of patient_master_timer.ABBRE_DESC
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public String getAbbreDesc() {
        return abbreDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_master_timer.ABBRE_DESC
     *
     * @param abbreDesc the value for patient_master_timer.ABBRE_DESC
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public void setAbbreDesc(String abbreDesc) {
        this.abbreDesc = abbreDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_master_timer.ABBRE_NAME
     *
     * @return the value of patient_master_timer.ABBRE_NAME
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public String getAbbreName() {
        return abbreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_master_timer.ABBRE_NAME
     *
     * @param abbreName the value for patient_master_timer.ABBRE_NAME
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public void setAbbreName(String abbreName) {
        this.abbreName = abbreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_master_timer.OPERATEDATE
     *
     * @return the value of patient_master_timer.OPERATEDATE
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public Date getOperatedate() {
        return operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_master_timer.OPERATEDATE
     *
     * @param operatedate the value for patient_master_timer.OPERATEDATE
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public void setOperatedate(Date operatedate) {
        this.operatedate = operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_master_timer.CREATEDATE
     *
     * @return the value of patient_master_timer.CREATEDATE
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_master_timer.CREATEDATE
     *
     * @param createdate the value for patient_master_timer.CREATEDATE
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_master_timer.UPDATEDATE
     *
     * @return the value of patient_master_timer.UPDATEDATE
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_master_timer.UPDATEDATE
     *
     * @param updatedate the value for patient_master_timer.UPDATEDATE
     *
     * @mbggenerated Thu Sep 01 16:17:07 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}