package com.ronglian.ch.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PatVisitExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public PatVisitExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInpatientNoIsNull() {
            addCriterion("INPATIENT_NO is null");
            return (Criteria) this;
        }

        public Criteria andInpatientNoIsNotNull() {
            addCriterion("INPATIENT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andInpatientNoEqualTo(String value) {
            addCriterion("INPATIENT_NO =", value, "inpatientNo");
            return (Criteria) this;
        }

        public Criteria andInpatientNoNotEqualTo(String value) {
            addCriterion("INPATIENT_NO <>", value, "inpatientNo");
            return (Criteria) this;
        }

        public Criteria andInpatientNoGreaterThan(String value) {
            addCriterion("INPATIENT_NO >", value, "inpatientNo");
            return (Criteria) this;
        }

        public Criteria andInpatientNoGreaterThanOrEqualTo(String value) {
            addCriterion("INPATIENT_NO >=", value, "inpatientNo");
            return (Criteria) this;
        }

        public Criteria andInpatientNoLessThan(String value) {
            addCriterion("INPATIENT_NO <", value, "inpatientNo");
            return (Criteria) this;
        }

        public Criteria andInpatientNoLessThanOrEqualTo(String value) {
            addCriterion("INPATIENT_NO <=", value, "inpatientNo");
            return (Criteria) this;
        }

        public Criteria andInpatientNoLike(String value) {
            addCriterion("INPATIENT_NO like", value, "inpatientNo");
            return (Criteria) this;
        }

        public Criteria andInpatientNoNotLike(String value) {
            addCriterion("INPATIENT_NO not like", value, "inpatientNo");
            return (Criteria) this;
        }

        public Criteria andInpatientNoIn(List<String> values) {
            addCriterion("INPATIENT_NO in", values, "inpatientNo");
            return (Criteria) this;
        }

        public Criteria andInpatientNoNotIn(List<String> values) {
            addCriterion("INPATIENT_NO not in", values, "inpatientNo");
            return (Criteria) this;
        }

        public Criteria andInpatientNoBetween(String value1, String value2) {
            addCriterion("INPATIENT_NO between", value1, value2, "inpatientNo");
            return (Criteria) this;
        }

        public Criteria andInpatientNoNotBetween(String value1, String value2) {
            addCriterion("INPATIENT_NO not between", value1, value2, "inpatientNo");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNull() {
            addCriterion("PATIENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNotNull() {
            addCriterion("PATIENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPatientIdEqualTo(String value) {
            addCriterion("PATIENT_ID =", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotEqualTo(String value) {
            addCriterion("PATIENT_ID <>", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThan(String value) {
            addCriterion("PATIENT_ID >", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThanOrEqualTo(String value) {
            addCriterion("PATIENT_ID >=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThan(String value) {
            addCriterion("PATIENT_ID <", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThanOrEqualTo(String value) {
            addCriterion("PATIENT_ID <=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLike(String value) {
            addCriterion("PATIENT_ID like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotLike(String value) {
            addCriterion("PATIENT_ID not like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIn(List<String> values) {
            addCriterion("PATIENT_ID in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotIn(List<String> values) {
            addCriterion("PATIENT_ID not in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdBetween(String value1, String value2) {
            addCriterion("PATIENT_ID between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotBetween(String value1, String value2) {
            addCriterion("PATIENT_ID not between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andVisitIdIsNull() {
            addCriterion("VISIT_ID is null");
            return (Criteria) this;
        }

        public Criteria andVisitIdIsNotNull() {
            addCriterion("VISIT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andVisitIdEqualTo(Integer value) {
            addCriterion("VISIT_ID =", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdNotEqualTo(Integer value) {
            addCriterion("VISIT_ID <>", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdGreaterThan(Integer value) {
            addCriterion("VISIT_ID >", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("VISIT_ID >=", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdLessThan(Integer value) {
            addCriterion("VISIT_ID <", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdLessThanOrEqualTo(Integer value) {
            addCriterion("VISIT_ID <=", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdIn(List<Integer> values) {
            addCriterion("VISIT_ID in", values, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdNotIn(List<Integer> values) {
            addCriterion("VISIT_ID not in", values, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdBetween(Integer value1, Integer value2) {
            addCriterion("VISIT_ID between", value1, value2, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdNotBetween(Integer value1, Integer value2) {
            addCriterion("VISIT_ID not between", value1, value2, "visitId");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToIsNull() {
            addCriterion("DEPT_ADMISSION_TO is null");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToIsNotNull() {
            addCriterion("DEPT_ADMISSION_TO is not null");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToEqualTo(String value) {
            addCriterion("DEPT_ADMISSION_TO =", value, "deptAdmissionTo");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToNotEqualTo(String value) {
            addCriterion("DEPT_ADMISSION_TO <>", value, "deptAdmissionTo");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToGreaterThan(String value) {
            addCriterion("DEPT_ADMISSION_TO >", value, "deptAdmissionTo");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_ADMISSION_TO >=", value, "deptAdmissionTo");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToLessThan(String value) {
            addCriterion("DEPT_ADMISSION_TO <", value, "deptAdmissionTo");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToLessThanOrEqualTo(String value) {
            addCriterion("DEPT_ADMISSION_TO <=", value, "deptAdmissionTo");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToLike(String value) {
            addCriterion("DEPT_ADMISSION_TO like", value, "deptAdmissionTo");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToNotLike(String value) {
            addCriterion("DEPT_ADMISSION_TO not like", value, "deptAdmissionTo");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToIn(List<String> values) {
            addCriterion("DEPT_ADMISSION_TO in", values, "deptAdmissionTo");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToNotIn(List<String> values) {
            addCriterion("DEPT_ADMISSION_TO not in", values, "deptAdmissionTo");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToBetween(String value1, String value2) {
            addCriterion("DEPT_ADMISSION_TO between", value1, value2, "deptAdmissionTo");
            return (Criteria) this;
        }

        public Criteria andDeptAdmissionToNotBetween(String value1, String value2) {
            addCriterion("DEPT_ADMISSION_TO not between", value1, value2, "deptAdmissionTo");
            return (Criteria) this;
        }

        public Criteria andAdmissionDateTimeIsNull() {
            addCriterion("ADMISSION_DATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andAdmissionDateTimeIsNotNull() {
            addCriterion("ADMISSION_DATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andAdmissionDateTimeEqualTo(Date value) {
            addCriterion("ADMISSION_DATE_TIME =", value, "admissionDateTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionDateTimeNotEqualTo(Date value) {
            addCriterion("ADMISSION_DATE_TIME <>", value, "admissionDateTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionDateTimeGreaterThan(Date value) {
            addCriterion("ADMISSION_DATE_TIME >", value, "admissionDateTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADMISSION_DATE_TIME >=", value, "admissionDateTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionDateTimeLessThan(Date value) {
            addCriterion("ADMISSION_DATE_TIME <", value, "admissionDateTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADMISSION_DATE_TIME <=", value, "admissionDateTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionDateTimeIn(List<Date> values) {
            addCriterion("ADMISSION_DATE_TIME in", values, "admissionDateTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionDateTimeNotIn(List<Date> values) {
            addCriterion("ADMISSION_DATE_TIME not in", values, "admissionDateTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionDateTimeBetween(Date value1, Date value2) {
            addCriterion("ADMISSION_DATE_TIME between", value1, value2, "admissionDateTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADMISSION_DATE_TIME not between", value1, value2, "admissionDateTime");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromIsNull() {
            addCriterion("DEPT_DISCHARGE_FROM is null");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromIsNotNull() {
            addCriterion("DEPT_DISCHARGE_FROM is not null");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromEqualTo(String value) {
            addCriterion("DEPT_DISCHARGE_FROM =", value, "deptDischargeFrom");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromNotEqualTo(String value) {
            addCriterion("DEPT_DISCHARGE_FROM <>", value, "deptDischargeFrom");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromGreaterThan(String value) {
            addCriterion("DEPT_DISCHARGE_FROM >", value, "deptDischargeFrom");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_DISCHARGE_FROM >=", value, "deptDischargeFrom");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromLessThan(String value) {
            addCriterion("DEPT_DISCHARGE_FROM <", value, "deptDischargeFrom");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromLessThanOrEqualTo(String value) {
            addCriterion("DEPT_DISCHARGE_FROM <=", value, "deptDischargeFrom");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromLike(String value) {
            addCriterion("DEPT_DISCHARGE_FROM like", value, "deptDischargeFrom");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromNotLike(String value) {
            addCriterion("DEPT_DISCHARGE_FROM not like", value, "deptDischargeFrom");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromIn(List<String> values) {
            addCriterion("DEPT_DISCHARGE_FROM in", values, "deptDischargeFrom");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromNotIn(List<String> values) {
            addCriterion("DEPT_DISCHARGE_FROM not in", values, "deptDischargeFrom");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromBetween(String value1, String value2) {
            addCriterion("DEPT_DISCHARGE_FROM between", value1, value2, "deptDischargeFrom");
            return (Criteria) this;
        }

        public Criteria andDeptDischargeFromNotBetween(String value1, String value2) {
            addCriterion("DEPT_DISCHARGE_FROM not between", value1, value2, "deptDischargeFrom");
            return (Criteria) this;
        }

        public Criteria andDischargeDateTimeIsNull() {
            addCriterion("DISCHARGE_DATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andDischargeDateTimeIsNotNull() {
            addCriterion("DISCHARGE_DATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andDischargeDateTimeEqualTo(Date value) {
            addCriterion("DISCHARGE_DATE_TIME =", value, "dischargeDateTime");
            return (Criteria) this;
        }

        public Criteria andDischargeDateTimeNotEqualTo(Date value) {
            addCriterion("DISCHARGE_DATE_TIME <>", value, "dischargeDateTime");
            return (Criteria) this;
        }

        public Criteria andDischargeDateTimeGreaterThan(Date value) {
            addCriterion("DISCHARGE_DATE_TIME >", value, "dischargeDateTime");
            return (Criteria) this;
        }

        public Criteria andDischargeDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DISCHARGE_DATE_TIME >=", value, "dischargeDateTime");
            return (Criteria) this;
        }

        public Criteria andDischargeDateTimeLessThan(Date value) {
            addCriterion("DISCHARGE_DATE_TIME <", value, "dischargeDateTime");
            return (Criteria) this;
        }

        public Criteria andDischargeDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("DISCHARGE_DATE_TIME <=", value, "dischargeDateTime");
            return (Criteria) this;
        }

        public Criteria andDischargeDateTimeIn(List<Date> values) {
            addCriterion("DISCHARGE_DATE_TIME in", values, "dischargeDateTime");
            return (Criteria) this;
        }

        public Criteria andDischargeDateTimeNotIn(List<Date> values) {
            addCriterion("DISCHARGE_DATE_TIME not in", values, "dischargeDateTime");
            return (Criteria) this;
        }

        public Criteria andDischargeDateTimeBetween(Date value1, Date value2) {
            addCriterion("DISCHARGE_DATE_TIME between", value1, value2, "dischargeDateTime");
            return (Criteria) this;
        }

        public Criteria andDischargeDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("DISCHARGE_DATE_TIME not between", value1, value2, "dischargeDateTime");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIsNull() {
            addCriterion("MARITAL_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIsNotNull() {
            addCriterion("MARITAL_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusEqualTo(String value) {
            addCriterion("MARITAL_STATUS =", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotEqualTo(String value) {
            addCriterion("MARITAL_STATUS <>", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusGreaterThan(String value) {
            addCriterion("MARITAL_STATUS >", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusGreaterThanOrEqualTo(String value) {
            addCriterion("MARITAL_STATUS >=", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLessThan(String value) {
            addCriterion("MARITAL_STATUS <", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLessThanOrEqualTo(String value) {
            addCriterion("MARITAL_STATUS <=", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLike(String value) {
            addCriterion("MARITAL_STATUS like", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotLike(String value) {
            addCriterion("MARITAL_STATUS not like", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIn(List<String> values) {
            addCriterion("MARITAL_STATUS in", values, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotIn(List<String> values) {
            addCriterion("MARITAL_STATUS not in", values, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusBetween(String value1, String value2) {
            addCriterion("MARITAL_STATUS between", value1, value2, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotBetween(String value1, String value2) {
            addCriterion("MARITAL_STATUS not between", value1, value2, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andBodyWeightIsNull() {
            addCriterion("BODY_WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andBodyWeightIsNotNull() {
            addCriterion("BODY_WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andBodyWeightEqualTo(BigDecimal value) {
            addCriterion("BODY_WEIGHT =", value, "bodyWeight");
            return (Criteria) this;
        }

        public Criteria andBodyWeightNotEqualTo(BigDecimal value) {
            addCriterion("BODY_WEIGHT <>", value, "bodyWeight");
            return (Criteria) this;
        }

        public Criteria andBodyWeightGreaterThan(BigDecimal value) {
            addCriterion("BODY_WEIGHT >", value, "bodyWeight");
            return (Criteria) this;
        }

        public Criteria andBodyWeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BODY_WEIGHT >=", value, "bodyWeight");
            return (Criteria) this;
        }

        public Criteria andBodyWeightLessThan(BigDecimal value) {
            addCriterion("BODY_WEIGHT <", value, "bodyWeight");
            return (Criteria) this;
        }

        public Criteria andBodyWeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BODY_WEIGHT <=", value, "bodyWeight");
            return (Criteria) this;
        }

        public Criteria andBodyWeightIn(List<BigDecimal> values) {
            addCriterion("BODY_WEIGHT in", values, "bodyWeight");
            return (Criteria) this;
        }

        public Criteria andBodyWeightNotIn(List<BigDecimal> values) {
            addCriterion("BODY_WEIGHT not in", values, "bodyWeight");
            return (Criteria) this;
        }

        public Criteria andBodyWeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BODY_WEIGHT between", value1, value2, "bodyWeight");
            return (Criteria) this;
        }

        public Criteria andBodyWeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BODY_WEIGHT not between", value1, value2, "bodyWeight");
            return (Criteria) this;
        }

        public Criteria andBodyHeightIsNull() {
            addCriterion("BODY_HEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andBodyHeightIsNotNull() {
            addCriterion("BODY_HEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andBodyHeightEqualTo(BigDecimal value) {
            addCriterion("BODY_HEIGHT =", value, "bodyHeight");
            return (Criteria) this;
        }

        public Criteria andBodyHeightNotEqualTo(BigDecimal value) {
            addCriterion("BODY_HEIGHT <>", value, "bodyHeight");
            return (Criteria) this;
        }

        public Criteria andBodyHeightGreaterThan(BigDecimal value) {
            addCriterion("BODY_HEIGHT >", value, "bodyHeight");
            return (Criteria) this;
        }

        public Criteria andBodyHeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BODY_HEIGHT >=", value, "bodyHeight");
            return (Criteria) this;
        }

        public Criteria andBodyHeightLessThan(BigDecimal value) {
            addCriterion("BODY_HEIGHT <", value, "bodyHeight");
            return (Criteria) this;
        }

        public Criteria andBodyHeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BODY_HEIGHT <=", value, "bodyHeight");
            return (Criteria) this;
        }

        public Criteria andBodyHeightIn(List<BigDecimal> values) {
            addCriterion("BODY_HEIGHT in", values, "bodyHeight");
            return (Criteria) this;
        }

        public Criteria andBodyHeightNotIn(List<BigDecimal> values) {
            addCriterion("BODY_HEIGHT not in", values, "bodyHeight");
            return (Criteria) this;
        }

        public Criteria andBodyHeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BODY_HEIGHT between", value1, value2, "bodyHeight");
            return (Criteria) this;
        }

        public Criteria andBodyHeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BODY_HEIGHT not between", value1, value2, "bodyHeight");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("CREATEBY is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("CREATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(String value) {
            addCriterion("CREATEBY =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(String value) {
            addCriterion("CREATEBY <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(String value) {
            addCriterion("CREATEBY >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEBY >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(String value) {
            addCriterion("CREATEBY <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(String value) {
            addCriterion("CREATEBY <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLike(String value) {
            addCriterion("CREATEBY like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotLike(String value) {
            addCriterion("CREATEBY not like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<String> values) {
            addCriterion("CREATEBY in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<String> values) {
            addCriterion("CREATEBY not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(String value1, String value2) {
            addCriterion("CREATEBY between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(String value1, String value2) {
            addCriterion("CREATEBY not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNull() {
            addCriterion("UPDATEBY is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNotNull() {
            addCriterion("UPDATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyEqualTo(String value) {
            addCriterion("UPDATEBY =", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotEqualTo(String value) {
            addCriterion("UPDATEBY <>", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThan(String value) {
            addCriterion("UPDATEBY >", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATEBY >=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThan(String value) {
            addCriterion("UPDATEBY <", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThanOrEqualTo(String value) {
            addCriterion("UPDATEBY <=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLike(String value) {
            addCriterion("UPDATEBY like", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotLike(String value) {
            addCriterion("UPDATEBY not like", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIn(List<String> values) {
            addCriterion("UPDATEBY in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotIn(List<String> values) {
            addCriterion("UPDATEBY not in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyBetween(String value1, String value2) {
            addCriterion("UPDATEBY between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotBetween(String value1, String value2) {
            addCriterion("UPDATEBY not between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNull() {
            addCriterion("UPDATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNotNull() {
            addCriterion("UPDATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateEqualTo(Date value) {
            addCriterion("UPDATEDATE =", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotEqualTo(Date value) {
            addCriterion("UPDATEDATE <>", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThan(Date value) {
            addCriterion("UPDATEDATE >", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATEDATE >=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThan(Date value) {
            addCriterion("UPDATEDATE <", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATEDATE <=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIn(List<Date> values) {
            addCriterion("UPDATEDATE in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotIn(List<Date> values) {
            addCriterion("UPDATEDATE not in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateBetween(Date value1, Date value2) {
            addCriterion("UPDATEDATE between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATEDATE not between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("FLAG is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Integer value) {
            addCriterion("FLAG =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Integer value) {
            addCriterion("FLAG <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Integer value) {
            addCriterion("FLAG >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("FLAG >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Integer value) {
            addCriterion("FLAG <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Integer value) {
            addCriterion("FLAG <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Integer> values) {
            addCriterion("FLAG in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Integer> values) {
            addCriterion("FLAG not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Integer value1, Integer value2) {
            addCriterion("FLAG between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("FLAG not between", value1, value2, "flag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pat_visit
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 07 14:27:05 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pat_visit
     *
     * @mbggenerated Wed Sep 07 14:27:05 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}