package com.ronglian.security.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ronglian.security.model.SysOrganizationResource;
import com.ronglian.security.model.SysOrganizationResourceExample;
import com.ronglian.security.model.SysOrganizationResourceWithBLOBs;

public interface SysOrganizationResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int countByExample(SysOrganizationResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int deleteByExample(SysOrganizationResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int deleteByPrimaryKey(byte[] id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int insert(SysOrganizationResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int insertSelective(SysOrganizationResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    List<SysOrganizationResourceWithBLOBs> selectByExampleWithBLOBs(SysOrganizationResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    List<SysOrganizationResource> selectByExample(SysOrganizationResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    SysOrganizationResourceWithBLOBs selectByPrimaryKey(byte[] id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysOrganizationResourceWithBLOBs record, @Param("example") SysOrganizationResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") SysOrganizationResourceWithBLOBs record, @Param("example") SysOrganizationResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int updateByExample(@Param("record") SysOrganizationResource record, @Param("example") SysOrganizationResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int updateByPrimaryKeySelective(SysOrganizationResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(SysOrganizationResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_resource
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int updateByPrimaryKey(SysOrganizationResource record);
}