package com.ronglian.security.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ronglian.security.model.SysRoles;
import com.ronglian.security.model.SysRolesExample;

public interface SysRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int countByExample(SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int deleteByExample(SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int insert(SysRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int insertSelective(SysRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    List<SysRoles> selectByExample(SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    SysRoles selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysRoles record, @Param("example") SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int updateByExample(@Param("record") SysRoles record, @Param("example") SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int updateByPrimaryKeySelective(SysRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated Wed Jul 13 16:33:37 CST 2016
     */
    int updateByPrimaryKey(SysRoles record);
}